language: node_js
node_js:
 - "node"
 - "9.0"
 - "7.0"
before_script:
  - npm install -g xo ava nyc yarn && yarn
cache:
  directories:
     - "node_modules"
script: 
  - npm run travis
  - npm run build

after_success: npm run coverage