language: node_js
node_js:
 - "node"
before_install:
  - npm install -g greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
  - npm install -g xo ava nyc npx yarn && yarn
after_script:
  - greenkeeper-lockfile-upload
cache:
  directories:
     - "node_modules"
script: 
  - npm run travis
  - npm run build

after_success: npm run coverage
